USE NEW_SCHEMA;
select * from playstore_reviews_cleaned1;
select * from playstore_apps_cleaned;
SELECT App ,Rating FROM playstore_apps_cleaned;
# 1) Which apps have the highest rating in the given available dataset?
select App,rating from playstore_apps_cleaned
order by Rating desc
limit 30;  #listing only top 30 apps rating wise 

# 2)What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top?
select App,Rating,Reviews,Installs  from playstore_apps_cleaned
order by Rating desc
limit 30;
 # 3) Which app has the highest number of reviews? 
-- Also, mention the number of reviews and category of the app
select app,reviews,category from playstore_apps_cleaned
order by reviews desc
limit 1;
# 4)What is the total amount of revenue generated by the google play store by hosting apps? 
-- (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
select sum(installs*price) as revenue from playstore_apps_cleaned;

# 5) Which Category of google play store apps has the highest number of installs?
-- also, find out the total number of installs for that particular category.

select distinct Category,installs from playstore_apps_cleaned
order by installs desc
limit 3;

# 6)  Which Genre has the most number of published apps?

SELECT Genres,
		COUNT(rating) as no_of_published
FROM playstore_apps_cleaned
GROUP BY Genres
ORDER BY 2 DESC
LIMIT 3;

# 7) Provide the list of all games ordered in such a way that the game that has 
-- the highest number of installs is displayed on the top(to avoid duplicate results use distinct)
select distinct app,category,Installs
from playstore_apps_cleaned
where category="Game"
order by Installs desc
limit 10;

# 8)  Provide the list of apps that can work on android version 4.0.3 and UP.?
SELECT App,
		`Android Ver`
FROM playstore_apps_cleaned
WHERE `Android Ver` >= '4.0.3 and up';

#9) How many apps from the given data set are free? Also, provide the number of paid apps.?
 select count(app) as free_app,Type
from playstore_apps_cleaned
 Group by type;
 
 #10) Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
 
 SELECT App,
		Category,
                Reviews
FROM playstore_apps_cleaned
WHERE Category = 'DATING'
LIMIT 1;

#11)  Get the number of reviews having positive sentiment and number of reviews
--  having negative sentiment for the app 10 best foods for you and compare them.
SELECT App,
		Sentiment,
                COUNT(*) Sentiment_Count
FROM playstore_reviews_cleaned1
WHERE App = '10 Best Foods for You' 
GROUP BY Sentiment;

#12) Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT *
FROM playstore_reviews_cleaned1
WHERE App = 'ASUS SuperNote' AND Sentiment_Polarity = 1 AND Sentiment_Subjectivity = 1;

#13)   Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat ?
SELECT *
FROM playstore_reviews_cleaned1
WHERE App = 'Abs Training-Burn belly fat' AND Sentiment = 'Neutral';

#14) Extract all negative sentiment reviews for 
-- Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity?

SELECT *
FROM playstore_reviews_cleaned1
WHERE App = 'Adobe Acrobat Reader' AND Sentiment = 'Negative';








 
 
 



